/* Source: ADCD 2.1
 * Section: e-release-2-changes-that-can-affect-compatibility-audio
 * Library: libraries
 * ADCD reference: libraries/e-release-2-changes-that-can-affect-compatibility-audio.md
 */

    is possible.  Check your return values from [OpenDevice()](../Libraries_Manual_guide/node029E.html).  This also
    means audio.device cannot be opened during 2.0 Strap unless
    [InitResident()](../Libraries_Manual_guide/node0419.html#line28)ed first.  If OpenDevice() of audio.device fails during
    strap, you must [FindResident()](../Includes_and_Autodocs_2._guide/node0350.html)/InitResident() audio.device, and then
    try OpenDevice() again.  There will be a small memory loss (until
    reboot) generated by the first opener of audio.device or
    narrator.device (memory used in building of audio.device's base).
