/* Source: ADCD 2.1
 * Section: devices-dev-examples-swap-buttons-c
 * Library: devices
 * ADCD reference: devices/devices-dev-examples-swap-buttons-c.md
 */

                move.w  ie_Code(a0),d0                  ; Get code...
                move.w  d0,d1                           ; Save...
                and.w   #$7F,d0                         ; Mask UP_PREFIX
                cmp.w   #IECODE_LBUTTON,d0              ; Check for Left...
                beq.s   SwapThem                        ; If so, swap...
                cmp.w   #IECODE_RBUTTON,d0              ; Check for Right..
                bne.s   NextEvent                       ; If not, next...
