/* Source: ADCD 2.1
 * Section: cd-device-cd-addchangeint
 * Library: autodocs-3.5
 * ADCD reference: autodocs-3.5/cd-device-cd-addchangeint.md
 */

       This command lets you add a software interrupt handler to the
       disk device that gets invoked whenever a disk insertion or removal
       occurs.

       You must pass in a properly initialized Exec [Interrupt](../Includes_and_Autodocs_3._guide/node061D.html#line21) structure
       and be prepared to deal with disk insertions/removals immediately.
       The interrupt is generated by the exec [Cause](../Includes_and_Autodocs_3._guide/node01F4.html) function, so you must
       preserve A6.

       To set up the handler, an [Interrupt](../Includes_and_Autodocs_3._guide/node061D.html#line21) structure must be initialized.
       This structure is supplied as the io_Data to the CD_ADDCHANGEINT
       command.  The handler then gets linked into the handler chain and
       gets invoked whenever a disk change happens.  You must eventually
       remove the handler before you exit.

       This command only returns when the handler is removed. That is,
       the device holds onto the IO request until the [CD_REMCHANGEINT](../Includes_and_Autodocs_3._guide/node00B4.html) command
       is executed with that same IO request.  Hence, you must use [SendIO()](../Includes_and_Autodocs_3._guide/node0236.html)
       with this command.
