#!/bin/bash
#
# test-fsemu.sh -- Automated FS-UAE testing for libSDL2-amigaos3
#
# Boots FS-UAE with RTG enabled, runs the ARexx test harness inside
# AmigaOS, captures results via shared WORK: volume, reports TAP output.
#
# Usage:
#   scripts/test-fsemu.sh               # Build + run all tests
#   scripts/test-fsemu.sh --no-build    # Skip make examples
#   scripts/test-fsemu.sh --timeout 180 # Override timeout (default 120s)
#
# Architecture:
#   1. Build examples via Docker (make examples)
#   2. Copy ARexx harness + binaries to build/amiga/ (WORK:)
#   3. Install User-Startup to build/system/S/
#   4. Launch FS-UAE with toolchain/configs/sdl2-test.fs-uae
#   5. Poll for build/amiga/test_summary.txt (sentinel: tests_done)
#   6. Parse results into TAP format
#   7. Kill FS-UAE by PID (never pkill -f)
#   8. Exit 0 (all pass) or 1 (any fail / timeout)
#
# Prerequisites:
#   - Docker (for make examples cross-compile)
#   - FS-UAE with RTG-capable config
#   - Kickstart 3.1 A4000 ROM
#   - Bootable WB 3.1 at build/system/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SYSTEM_DIR="$PROJECT_DIR/build/system"
AMIGA_DIR="$PROJECT_DIR/build/amiga"
STATE_DIR="$PROJECT_DIR/build/fs-uae-state"
FS_UAE_CONFIG="$PROJECT_DIR/toolchain/configs/sdl2-test.fs-uae"
KICKSTART="$HOME/Documents/FS-UAE/Kickstarts/kick3.1-a4000.rom"
TIMEOUT_SECONDS=120
BUILD_EXAMPLES=true
SINGLE_TARGET=""
FSUAE_PID_FILE="$STATE_DIR/fs-uae.pid"

# Prefer a locally built FS-UAE fork, fall back to system install
FSUAE_FORK="$HOME/Developer/fs-uae/fs-uae"
if [ -x "$FSUAE_FORK" ]; then
    FSUAE_BIN="$FSUAE_FORK"
else
    FSUAE_BIN="fs-uae"
fi

# Terminal colours (disabled if not a tty)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    CYAN='\033[0;36m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' CYAN='' NC=''
fi

# ============================================================
# Argument parsing
# ============================================================
while [ $# -gt 0 ]; do
    case "$1" in
        --no-build)   BUILD_EXAMPLES=false ;;
        --target)     shift; SINGLE_TARGET="$1" ;;
        --target=*)   SINGLE_TARGET="${1#*=}" ;;
        --timeout)    shift; TIMEOUT_SECONDS="$1" ;;
        --timeout=*)  TIMEOUT_SECONDS="${1#*=}" ;;
        -h|--help)
            echo "Usage: $0 [--no-build] [--target NAME] [--timeout N]"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
    shift
done

# ============================================================
# Pre-flight checks
# ============================================================
preflight() {
    local errors=0

    if ! command -v docker >/dev/null 2>&1; then
        echo -e "${RED}ERROR: docker not found -- required for make examples${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ ! -x "$FSUAE_BIN" ] && ! command -v "$FSUAE_BIN" >/dev/null 2>&1; then
        echo -e "${RED}ERROR: FS-UAE not found (tried $FSUAE_FORK and fs-uae in PATH)${NC}" >&2
        echo -e "${RED}       Install: brew install fs-uae${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ ! -f "$KICKSTART" ]; then
        echo -e "${RED}ERROR: Kickstart ROM not found at $KICKSTART${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ ! -d "$SYSTEM_DIR/S" ]; then
        echo -e "${RED}ERROR: No bootable system at $SYSTEM_DIR/S/${NC}" >&2
        echo -e "${RED}       Set up WB 3.1 directory system first.${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ ! -f "$AMIGA_DIR/UAEQuit" ]; then
        echo -e "${RED}ERROR: UAEQuit binary not found at $AMIGA_DIR/UAEQuit${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ ! -f "$FS_UAE_CONFIG" ]; then
        echo -e "${RED}ERROR: FS-UAE config not found at $FS_UAE_CONFIG${NC}" >&2
        errors=$((errors + 1))
    fi

    if [ "$errors" -gt 0 ]; then
        echo -e "${RED}Pre-flight failed with $errors error(s). Aborting.${NC}" >&2
        exit 1
    fi
}

# ============================================================
# Build step
# ============================================================
build_examples() {
    echo -e "${CYAN}==> Building examples via Docker...${NC}"
    make -C "$PROJECT_DIR" examples
    echo -e "${GREEN}    Build complete.${NC}"
}

# ============================================================
# Generate ARexx harness from tests.txt
# ============================================================
generate_rexx_harness() {
    local rexx="$AMIGA_DIR/run_tests.rexx"

    cat > "$rexx" << 'REXX_HEADER'
/* SDL2 AmigaOS3 Automated Test Harness (generated by test-fsemu.sh)
 * Pure ASCII only. Use ~= for not-equal. */
OPTIONS FAILAT 21

CALL main
EXIT

main:
    ADDRESS COMMAND 'MakeDir >NIL: WORK:results'
    total_tests  = 0
    passed_tests = 0
    failed_tests = 0

    SAY 'SDL2 AmigaOS3 Test Harness starting'
    ADDRESS COMMAND 'Wait 3'

    ADDRESS COMMAND 'Delete >NIL: WORK:test_summary.txt'
    IF OPEN('sf', 'WORK:test_summary.txt', 'W') THEN
        CALL CLOSE('sf')

REXX_HEADER

    # Add one CALL per test from tests.txt (or single target)
    # Skip tier M (manual/interactive) tests unless explicitly targeted
    while IFS=' ' read -r name category tier rest; do
        case "$name" in '#'*|'') continue ;; esac
        # If single target mode, skip non-matching tests
        if [ -n "$SINGLE_TARGET" ] && [ "$name" != "$SINGLE_TARGET" ]; then
            continue
        fi
        # Skip manual (M) tier tests in automated runs
        if [ -z "$SINGLE_TARGET" ] && [ "$tier" = "M" ]; then
            continue
        fi
        echo "    CALL run_one_test '$name', '$category'" >> "$rexx"
    done < "$PROJECT_DIR/tests.txt"

    cat >> "$rexx" << 'REXX_FOOTER'

    footer_line = 'SUMMARY total=' || total_tests || ' passed=' || passed_tests || ' failed=' || failed_tests
    IF OPEN('sf', 'WORK:test_summary.txt', 'A') THEN DO
        CALL WRITELN('sf', footer_line)
        CALL CLOSE('sf')
    END

    SAY footer_line

    IF OPEN('dn', 'WORK:tests_done', 'W') THEN DO
        CALL WRITELN('dn', 'done')
        CALL CLOSE('dn')
    END

    ADDRESS COMMAND 'Wait 1'
    ADDRESS COMMAND 'WORK:UAEQuit'
    RETURN

run_one_test: PROCEDURE EXPOSE total_tests passed_tests failed_tests
    PARSE ARG testname, category

    total_tests = total_tests + 1

    result_file = 'WORK:results/' || testname || '.txt'
    binary      = 'WORK:' || testname
    script_file = 'T:sdl2_run_' || testname
    rc_file     = 'T:sdl2_rc_' || testname

    ADDRESS COMMAND 'Delete >NIL: ' || result_file
    ADDRESS COMMAND 'Delete >NIL: ' || script_file
    ADDRESS COMMAND 'Delete >NIL: ' || rc_file

    IF OPEN('scr', script_file, 'W') THEN DO
        CALL WRITELN('scr', 'FailAt 21')
        CALL WRITELN('scr', binary '>' result_file)
        CALL WRITELN('scr', 'Echo >' || rc_file || ' $RC')
        CALL CLOSE('scr')
    END
    ELSE DO
        SAY 'ERROR: Cannot create script file' script_file
        failed_tests = failed_tests + 1
        RETURN
    END

    ADDRESS COMMAND 'Execute ' || script_file

    test_rc = 0
    IF OPEN('rcf', rc_file, 'R') THEN DO
        rcline = READLN('rcf')
        CALL CLOSE('rcf')
        IF DATATYPE(STRIP(rcline), 'W') THEN test_rc = STRIP(rcline)
    END
    ELSE
        test_rc = 20

    ADDRESS COMMAND 'Delete >NIL: ' || script_file
    ADDRESS COMMAND 'Delete >NIL: ' || rc_file

    IF ~EXISTS(result_file) THEN DO
        IF OPEN('rf2', result_file, 'W') THEN DO
            CALL WRITELN('rf2', 'TEST BINARY NOT FOUND OR CRASHED')
            CALL CLOSE('rf2')
        END
        test_rc = 20
    END

    IF test_rc = 0 THEN DO
        outcome = 'PASS'
        passed_tests = passed_tests + 1
    END
    ELSE DO
        outcome = 'FAIL'
        failed_tests = failed_tests + 1
    END

    line = outcome || ' ' || testname || ' RC=' || test_rc || ' [' || category || ']'

    IF OPEN('rf3', result_file, 'A') THEN DO
        CALL WRITELN('rf3', line)
        CALL CLOSE('rf3')
    END

    IF OPEN('sf', 'WORK:test_summary.txt', 'A') THEN DO
        CALL WRITELN('sf', line)
        CALL CLOSE('sf')
    END

    SAY line
    RETURN
REXX_FOOTER

    echo "    Generated run_tests.rexx from tests.txt"
}

# ============================================================
# Deploy: copy harness + binaries to WORK:
# ============================================================
deploy() {
    echo -e "${CYAN}==> Deploying test binaries and harness to build/amiga/...${NC}"

    # Create results subdirectory
    mkdir -p "$AMIGA_DIR/results"

    # Clear previous results
    rm -f "$AMIGA_DIR/results/"*.txt 2>/dev/null || true
    rm -f "$AMIGA_DIR/test_summary.txt" 2>/dev/null || true
    rm -f "$AMIGA_DIR/tests_done" 2>/dev/null || true
    # Also remove any FS-UAE metadata sidecars for these
    rm -f "$AMIGA_DIR/test_summary.txt.uaem" 2>/dev/null || true
    rm -f "$AMIGA_DIR/tests_done.uaem" 2>/dev/null || true

    # Copy test binaries from examples/ to build/amiga/
    # Read test list from tests.txt (single source of truth)
    while IFS=' ' read -r name category tier; do
        # Skip comments and blank lines
        case "$name" in '#'*|'') continue ;; esac
        if [ -f "$PROJECT_DIR/examples/$name" ]; then
            cp "$PROJECT_DIR/examples/$name" "$AMIGA_DIR/$name"
            echo "    Copied $name"
        else
            echo -e "${YELLOW}    WARNING: $name not found in examples/ -- skipping${NC}"
        fi
    done < "$PROJECT_DIR/tests.txt"

    # Generate ARexx harness from tests.txt
    generate_rexx_harness

    echo -e "${GREEN}    Deploy complete.${NC}"
}

# ============================================================
# Install User-Startup
# ============================================================
install_user_startup() {
    echo -e "${CYAN}==> Installing User-Startup...${NC}"
    mkdir -p "$SYSTEM_DIR/S"
    cp "$SCRIPT_DIR/amiga/User-Startup" "$SYSTEM_DIR/S/User-Startup"
    echo -e "${GREEN}    Installed to $SYSTEM_DIR/S/User-Startup${NC}"
}

# ============================================================
# Cleanup handler: kill FS-UAE by PID on exit
# ============================================================
fsuae_pid=""
cleanup() {
    if [ -n "$fsuae_pid" ] && kill -0 "$fsuae_pid" 2>/dev/null; then
        echo -e "${YELLOW}Killing FS-UAE (PID $fsuae_pid)...${NC}"
        kill "$fsuae_pid" 2>/dev/null || true
        wait "$fsuae_pid" 2>/dev/null || true
    fi
    # Clean up PID file
    rm -f "$FSUAE_PID_FILE" 2>/dev/null || true
}
trap cleanup EXIT

# ============================================================
# Launch FS-UAE
# ============================================================
launch_fsuae() {
    mkdir -p "$STATE_DIR"

    echo -e "${CYAN}==> Launching FS-UAE (timeout: ${TIMEOUT_SECONDS}s)...${NC}"
    echo "    Config: $FS_UAE_CONFIG"
    echo "    Binary: $FSUAE_BIN"

    "$FSUAE_BIN" "$FS_UAE_CONFIG" \
        >"$STATE_DIR/fsuae.log" 2>&1 &
    fsuae_pid=$!

    # Save PID for external reference / crash recovery
    echo "$fsuae_pid" > "$FSUAE_PID_FILE"

    echo "    FS-UAE started (PID $fsuae_pid)"
}

# ============================================================
# Poll for results with timeout
# ============================================================
wait_for_results() {
    local start_time
    start_time=$(date +%s)
    local sentinel="$AMIGA_DIR/tests_done"
    local summary="$AMIGA_DIR/test_summary.txt"
    local last_msg_time=0
    local check_interval=2

    echo -e "${CYAN}==> Waiting for tests to complete...${NC}"

    while true; do
        local now
        now=$(date +%s)
        local elapsed=$(( now - start_time ))

        # Check if FS-UAE exited on its own (UAEQuit called)
        if ! kill -0 "$fsuae_pid" 2>/dev/null; then
            wait "$fsuae_pid" 2>/dev/null || true
            fsuae_pid=""
            echo "    FS-UAE exited after ${elapsed}s"
            # Give filesystem a moment to flush
            sleep 1
            return 0
        fi

        # Check for sentinel file (written just before UAEQuit)
        if [ -f "$sentinel" ]; then
            echo "    Sentinel detected after ${elapsed}s -- tests complete"
            # Give FS-UAE a moment to process UAEQuit
            sleep 2
            if kill -0 "$fsuae_pid" 2>/dev/null; then
                echo "    UAEQuit pending -- killing FS-UAE"
                kill "$fsuae_pid" 2>/dev/null || true
                wait "$fsuae_pid" 2>/dev/null || true
            fi
            fsuae_pid=""
            return 0
        fi

        # Check for summary directly (belt and suspenders)
        if [ -f "$summary" ]; then
            # Only trust it if we also see SUMMARY line (harness fully completed)
            if grep -q "^SUMMARY" "$summary" 2>/dev/null; then
                echo "    Summary file complete after ${elapsed}s"
                sleep 2
                if kill -0 "$fsuae_pid" 2>/dev/null; then
                    kill "$fsuae_pid" 2>/dev/null || true
                    wait "$fsuae_pid" 2>/dev/null || true
                fi
                fsuae_pid=""
                return 0
            fi
        fi

        # Check for Guru Meditation in FS-UAE log
        if [ -f "$STATE_DIR/fsuae.log" ]; then
            if grep -q -i "guru\|Alert\|Exception" "$STATE_DIR/fsuae.log" 2>/dev/null; then
                echo -e "${RED}    GURU MEDITATION detected in FS-UAE log!${NC}"
                # Don't return error yet -- wait for timeout so we can collect logs
            fi
        fi

        # Timeout
        if [ "$elapsed" -ge "$TIMEOUT_SECONDS" ]; then
            echo -e "${RED}    TIMEOUT after ${TIMEOUT_SECONDS}s${NC}"
            if kill -0 "$fsuae_pid" 2>/dev/null; then
                kill "$fsuae_pid" 2>/dev/null || true
                wait "$fsuae_pid" 2>/dev/null || true
            fi
            fsuae_pid=""
            return 1
        fi

        # Progress message every 10 seconds
        if [ $(( elapsed - last_msg_time )) -ge 10 ]; then
            echo "    ... ${elapsed}s elapsed (waiting for AmigaOS boot + tests)"
            last_msg_time=$elapsed
        fi

        sleep "$check_interval"
    done
}

# ============================================================
# Parse results into TAP format
# ============================================================
parse_results() {
    local summary="$AMIGA_DIR/test_summary.txt"
    local tap_count=0
    local pass_count=0
    local fail_count=0
    local total_count=0

    if [ ! -f "$summary" ]; then
        echo "TAP version 13"
        echo "1..0"
        echo "Bail out! No test_summary.txt found -- tests did not run"
        return 1
    fi

    # Count tests first (lines starting with PASS or FAIL)
    total_count=$(grep -c "^PASS\|^FAIL" "$summary" 2>/dev/null || echo 0)

    echo "TAP version 13"
    echo "1..$total_count"

    while IFS= read -r line; do
        case "$line" in
            PASS*)
                tap_count=$((tap_count + 1))
                pass_count=$((pass_count + 1))
                # Extract test name: "PASS test_init RC=0 [SMOKE]"
                testname=$(echo "$line" | awk '{print $2}')
                rc=$(echo "$line" | grep -o 'RC=[0-9]*' | cut -d= -f2)
                category=$(echo "$line" | grep -o '\[.*\]' | tr -d '[]')
                echo "ok $tap_count - $testname ($category) RC=$rc"
                ;;
            FAIL*)
                tap_count=$((tap_count + 1))
                fail_count=$((fail_count + 1))
                testname=$(echo "$line" | awk '{print $2}')
                rc=$(echo "$line" | grep -o 'RC=[0-9]*' | cut -d= -f2)
                category=$(echo "$line" | grep -o '\[.*\]' | tr -d '[]')
                echo "not ok $tap_count - $testname ($category) RC=$rc"
                # Show per-test output if available
                result_file="$AMIGA_DIR/results/${testname}.txt"
                if [ -f "$result_file" ]; then
                    echo "  ---"
                    echo "  output: |"
                    while IFS= read -r out_line; do
                        echo "    $out_line"
                    done < "$result_file"
                    echo "  ..."
                fi
                ;;
            SUMMARY*)
                # Parse footer: "SUMMARY total=4 passed=3 failed=1"
                echo "# $line"
                ;;
        esac
    done < "$summary"

    echo ""
    if [ "$fail_count" -eq 0 ] && [ "$total_count" -gt 0 ]; then
        echo -e "${GREEN}All $pass_count/$total_count tests passed.${NC}"
        return 0
    elif [ "$total_count" -eq 0 ]; then
        echo -e "${RED}No test results found.${NC}"
        return 1
    else
        echo -e "${RED}$fail_count/$total_count tests FAILED.${NC}"
        return 1
    fi
}

# ============================================================
# Show FS-UAE log tail on failure
# ============================================================
show_fsuae_log() {
    local log="$STATE_DIR/fsuae.log"
    if [ -f "$log" ]; then
        echo ""
        echo "--- FS-UAE log (last 30 lines) ---"
        tail -30 "$log"
        echo "----------------------------------"
    fi
}

# ============================================================
# MAIN
# ============================================================

echo ""
echo "SDL2 AmigaOS3 -- FS-UAE Test Suite"
echo "==================================="
echo ""

preflight

if [ "$BUILD_EXAMPLES" = true ]; then
    build_examples
fi

deploy
install_user_startup
launch_fsuae

# Wait for results; capture exit status
wait_result=0
wait_for_results || wait_result=$?

# Parse results into TAP
parse_result=0
parse_results || parse_result=$?

# Show FS-UAE log on any failure
if [ "$wait_result" -ne 0 ] || [ "$parse_result" -ne 0 ]; then
    show_fsuae_log
fi

echo ""
if [ "$wait_result" -ne 0 ]; then
    echo -e "${RED}FAILED: FS-UAE timed out or crashed.${NC}"
    exit 1
fi

if [ "$parse_result" -ne 0 ]; then
    exit 1
fi

exit 0
