/* Source: ADCD 2.1
 * Section: input-device-ind-addhandler
 * Library: autodocs-2.0
 * ADCD reference: autodocs-2.0/input-device-ind-addhandler.md
 */

    Add a function to the list of functions called to handle
    input events generated by this device.  The function is called
    as
        newInputEvents = Handler(inputEvents, handlerData);
        D0                       A0           A1
